version: '3.8'

services:
  portfolio:
    build:
      context: ./portfolio
      dockerfile: Dockerfile
    container_name: portfolio-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge